### ISSUE TITLE
PoC: OpenAppSec.io

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/open-appsec-poc#1]
https://www.openappsec.io

### Todos
- [x] CI pipeline (see configs repo)
- [x] Follow instructions from https://www.youtube.com/watch?v=IUgPHjLrJR8
    - [x] Add Acme Audit app (if possible)
    - [ ] Adopt Linux Nginx Playground: https://www.openappsec.io/playground
    - [ ] :zap: Somehow the nginx does not communicate with the open-appsec agent
- [ ] Initialize Antora Docs
    - [x] add playbook
    - [x] Build from docker compose
    - [ ] Custom Dockerfile for this docs?
    - [x] serve through reverse proxy
    - [x] Still, embedd docs in website-sommerfeld-io
    - [ ] Link Apps from docs startpage 
    - [ ] Maybe generate readme a little bit differently (not the same as the docs-startpage?)
    - [ ] Change Docs to single page served by an nginx? Bundle all Antora docs into Single Page Adoc, then generate HTML?
        - [ ] Checkout Antora Collector and Antora Assemler
        - [ ] Everything from docker compose
- [x] Add an intentionally insecure webapp
    - [x] serve through reverse proxy (7080)
- [x] Setup open-appsec https://docs.openappsec.io/getting-started/start-with-docker
    - [ ] Check why there are no monitoring events: https://my.openappsec.io ... Maybe the Acme Audit app can create some events?
- [ ] Try some attacks / put some load
    - [ ] Gatlin
    - [ ] Zap
    - [ ] ???
- [ ] Learn some of the concepts
    - [ ] What is an open-appsec agent? Write down in docs somewhere

### Enhancements
- [ ] Docs as startpage
    - [ ] Somehow add tiles or simething to highlight links to the applications etc.
- [x] Other services with context path but still through the reverse proxy
- [ ] Configure Nginx to use HTTPS for localhost
